# Dados de conexao com o banco H2
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:

        # Configuracao do cliente web do banco H2
  h2:
    console:
      enabled: true
      path: /h2-console

  # Configuracao para mostrar o SQL no console
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true


security:
  token:
    test:
      secret: api#avaliacao